require("risedev.core.options.options")
require("risedev.core.options.indentation")

-- require("risedev.core.keymaps.colemakLayer")
require("risedev.core.keymaps.deleteAndPaste")
require("risedev.core.keymaps.extra")
require("risedev.core.keymaps.insertMode")
require("risedev.core.keymaps.general")
require("risedev.core.keymaps.toggle")
require("risedev.core.keymaps.numpad")
-- require("risedev.core.keymaps.symbolsLayer")
require("risedev.core.keymaps.windowAndTabs")
